install node in pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,6 +5,19 @@
 # Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
 # Note that environment variables can be set in several places
 # See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
+image: node:18
+
+before_script:
+  - |
+    if ! command -v npm >/dev/null 2>&1; then
+      echo "npm not found, installing Node locally into $CI_PROJECT_DIR/.node"
+      NODE_VERSION=18.20.0
+      curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" -o node.tar.xz
+      mkdir -p .node
+      tar -xJf node.tar.xz -C .node --strip-components=1
+      export PATH="$CI_PROJECT_DIR/.node/bin:$PATH"
+    fi
+  - npm --version
 stages:
 - build
 - test
